# Generated by Django 4.2.29 on 2026-04-12 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SPSB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspostmedia',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_media', to='SPSB.newspost'),
        ),
    ]
