# Generated by Django 4.2.29 on 2026-04-21 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SPSB', '0007_volunteer'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='volunteer',
            new_name='SPSB_volunt_volunte_c949d8_idx',
            old_name='SPSB_volun_volunte_idx',
        ),
        migrations.RenameIndex(
            model_name='volunteer',
            new_name='SPSB_volunt_is_publ_43fb10_idx',
            old_name='SPSB_volun_is_publ_idx',
        ),
    ]
