# Generated by Django 4.2.29 on 2026-04-21 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SPSB', '0009_committeemember'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='committeemember',
            new_name='SPSB_commit_committ_7ecbca_idx',
            old_name='SPSB_commit_committe_idx',
        ),
        migrations.RenameIndex(
            model_name='committeemember',
            new_name='SPSB_commit_is_publ_50edd0_idx',
            old_name='SPSB_commit_is_publ_idx',
        ),
        migrations.RenameIndex(
            model_name='committeemember',
            new_name='SPSB_commit_positio_17c424_idx',
            old_name='SPSB_commit_position_idx',
        ),
    ]
