# Generated by Django 4.2.27 on 2026-04-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "SPSB",
            "0010_rename_spsb_commit_committe_idx_spsb_commit_committ_7ecbca_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="committeemember",
            name="username",
            field=models.CharField(
                default="",
                help_text="Unique identifier provided via Excel",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="username",
            field=models.CharField(
                default="",
                help_text="Unique identifier provided via Excel",
                max_length=20,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="committeemember",
            name="position",
            field=models.CharField(
                choices=[
                    ("president", "President"),
                    ("vice_president", "Vice President"),
                    ("secretary", "Secretary"),
                    ("general_secretary", "General Secretary"),
                    ("joint_secretary", "Joint Secretary"),
                    ("treasurer", "Treasurer"),
                    ("coordinator", "Coordinator"),
                    ("program_officer", "Program Officer"),
                    ("senior_program_officer", "Senior Program Officer"),
                    ("program_associate", "Program Associate"),
                    ("member", "Member"),
                    ("academic_councilor", "Academic Councilor"),
                ],
                default="member",
                help_text="Committee position/role",
                max_length=30,
            ),
        ),
    ]
